export const SUBTITLE_LANGUAGES = [
  { name: 'English',               code: 'en' },
  { name: 'Spanish',               code: 'es' },
  { name: 'French',                code: 'fr' },
  { name: 'German',                code: 'de' },
  { name: 'Portuguese',            code: 'pt' },
  { name: 'Italian',               code: 'it' },
  { name: 'Arabic',                code: 'ar' },
  { name: 'Hindi',                 code: 'hi' },
  { name: 'Japanese',              code: 'ja' },
  { name: 'Korean',                code: 'ko' },
  { name: 'Chinese (Simplified)',  code: 'zh' },
  { name: 'Chinese (Traditional)', code: 'zh-TW' },
  { name: 'Russian',               code: 'ru' },
  { name: 'Turkish',               code: 'tr' },
  { name: 'Dutch',                 code: 'nl' },
  { name: 'Polish',                code: 'pl' },
  { name: 'Indonesian',            code: 'id' },
  { name: 'Thai',                  code: 'th' },
  { name: 'Vietnamese',            code: 'vi' },
  { name: 'Swedish',               code: 'sv' },
  { name: 'Norwegian',             code: 'no' },
  { name: 'Danish',                code: 'da' },
  { name: 'Finnish',               code: 'fi' },
  { name: 'Greek',                 code: 'el' },
  { name: 'Czech',                 code: 'cs' },
  { name: 'Romanian',              code: 'ro' },
  { name: 'Hungarian',             code: 'hu' },
  { name: 'Hebrew',                code: 'he' },
]
